name: Lint
on:
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
